# Generated by Django 3.2.18 on 2023-04-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0004_bank_complaintypes_customergroup_department_insurance_package_province_vehiclemake_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomername', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('requirements', models.TextField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_city', to='configurations.cities')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_package', to='configurations.package')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_province', to='configurations.province')),
            ],
        ),
    ]
