from django.urls import path
from .views import (
    InventoryListView, InventoryDetailView, InventoryCreateView, InventoryUpdateView, InventoryDeleteView,
    TrackerDeviceListView,
    TrackerDeviceDetailView,
    TrackerDeviceCreateView,
    TrackerDeviceUpdateView,
    TrackerDeviceDeleteView,
    SimCreateView,
    SimListView,
    SimUpdateView,
    SimDeleteView,
    TrackerDeviceVendorListView, 
    TrackerDeviceVendorCreateView, 
    TrackerDeviceVendorUpdateView, 
    TrackerDeviceVendorDeleteView,
    TrackerDeviceModelListView,
    TrackerDeviceModelCreateView,
    TrackerDeviceModelUpdateView,
    TrackerDeviceModelDeleteView,
)
app_name = 'inventory'
urlpatterns = [
    path('', InventoryListView.as_view(), name='inventory_list'),
    path('<int:pk>/', InventoryDetailView.as_view(), name='inventory_detail'),
    path('new/', InventoryCreateView.as_view(), name='inventory_new'),
    path('<int:pk>/edit/', InventoryUpdateView.as_view(), name='inventory_edit'),
    path('<int:pk>/delete/', InventoryDeleteView.as_view(), name='inventory_delete'),
    path('trackerdevices/', TrackerDeviceListView.as_view(), name='trackerdevice_list'),
    path('trackerdevices/new', TrackerDeviceCreateView.as_view(), name='trackerdevice_new'),
    path('trackerdevices/<int:pk>/edit/', TrackerDeviceUpdateView.as_view(), name='trackerdevice_edit'),
    path('trackerdevices/<int:pk>/delete/', TrackerDeviceDeleteView.as_view(), name='trackerdevice_delete'),
    path('trackerdevices/<int:pk>/', TrackerDeviceDetailView.as_view(), name='trackerdevice_detail'),
    path('sims/', SimListView.as_view(), name='sim_list'),
    path('sims/new', SimCreateView.as_view(), name='sim_new'),
    path('sims/<int:pk>/edit/', SimUpdateView.as_view(), name='sim_update'),
    path('sims/<int:pk>/delete/', SimDeleteView.as_view(), name='sim_delete'),
    #path('sims/<int:pk>/', SimDetailView.as_view(), name='sim_detail'),
    path('vendor/', TrackerDeviceVendorListView.as_view(), name='trackerdevicevendor_list'),
    path('vendor/new/', TrackerDeviceVendorCreateView.as_view(), name='trackerdevicevendor_new'),
    path('vendor/<int:pk>/', TrackerDeviceVendorUpdateView.as_view(), name='trackerdevicevendor_edit'),
    path('vendor/<int:pk>/delete/', TrackerDeviceVendorDeleteView.as_view(), name='trackerdevicevendor_delete'),
    path('trackerdevicemodel/', TrackerDeviceModelListView.as_view(), name='trackerdevicemodel_list'),
    path('trackerdevicemodel/create/', TrackerDeviceModelCreateView.as_view(), name='trackerdevicemodel_create'),
    path('trackerdevicemodel/<int:pk>/update/', TrackerDeviceModelUpdateView.as_view(), name='trackerdevicemodel_update'),
    path('trackerdevicemodel/<int:pk>/delete/', TrackerDeviceModelDeleteView.as_view(), name='trackerdevicemodel_delete'),
]
