# Generated by Django 3.2.18 on 2023-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Agent'), (3, 'Installer')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_installer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
