# Generated by Django 3.2.18 on 2023-04-23 21:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230424_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
