# Generated by Django 3.2.18 on 2023-03-26 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_trackerdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.CharField(max_length=50)),
                ('ICC_ID', models.CharField(max_length=50)),
                ('OPERATOR', models.CharField(choices=[('zong', 'Zong'), ('ufone', 'Ufone'), ('warid', 'Warid'), ('mobilink', 'Mobilink'), ('telenor', 'Telenor')], max_length=50)),
                ('SIM_TYPE', models.CharField(choices=[('2g', '2G'), ('3g', '3G')], max_length=50)),
                ('PACKAGE', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_items', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
