# Generated by Django 3.2.18 on 2023-04-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20230404_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerdevice',
            name='price',
        ),
        migrations.AlterField(
            model_name='trackerdevice',
            name='model_number',
            field=models.CharField(choices=[('fmB920', 'FMB920'), ('FMB125', 'FMB125'), ('fmt100', 'FMT100'), ('gv300', 'GV300'), ('gv55', 'GV55')], max_length=255),
        ),
        migrations.AlterField(
            model_name='trackerdevice',
            name='vendor',
            field=models.CharField(choices=[('teltonika', 'Teltonika'), ('queclink', 'Queclink')], max_length=255),
        ),
    ]
