# Generated by Django 3.2.18 on 2023-04-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('companies', '0002_auto_20230410_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cities', to='configurations.cities'),
        ),
        migrations.AlterField(
            model_name='company',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_subscription', to='configurations.subscriptions'),
        ),
    ]
