# Generated by Django 3.2.18 on 2023-04-18 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20230416_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='renew_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
