# Generated by Django 3.2.18 on 2023-04-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address'),
        ('inventory', '0005_sim'),
        ('vehicles', '0002_alter_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_items', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='isTrackerInstalled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_items', to='inventory.sim'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trackerDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_items', to='inventory.trackerdevice'),
        ),
    ]
