# Generated by Django 3.2.18 on 2023-04-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_auto_20230419_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
