# Generated by Django 3.2.18 on 2023-03-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sim'),
        ('vehicles', '0002_alter_vehicle_color'),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackerinstallation',
            unique_together={('vehicle', 'tracker_device', 'sim')},
        ),
    ]
